eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

server:
  port: 8005

spring:
  application:
    name: zuul-service

zuul:
  routes:
    loginservice:
      path: /loginservice/**
      serviceId: LOGIN-SERVICE